name: VDSCP-BUILD

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04] #Only one OS is necessary
    steps:
      - uses: actions/checkout@v1
      # DEFAULT WORKFLOW
     # install dependencies
      - name: boost
        run: sudo apt update && sudo apt install libboost-all-dev
      - name: Build System Generation
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && cmake ../
      - name: Build VDSCP
        run: cmake --build $GITHUB_WORKSPACE/build/ --target VDSProject -- -j8
      - name: Build Tests
        run: |
          cmake --build $GITHUB_WORKSPACE/build/ --target VDSProject_test -- -j8
      - name: Run Tests
        run: |
          $GITHUB_WORKSPACE/build/src/test/VDSProject_test
